const canvas = document.getElementById('particles-canvas');
const ctx = canvas.getContext('2d');
canvas.width = window.innerWidth; canvas.height = window.innerHeight;
window.addEventListener('resize', ()=>{ canvas.width = window.innerWidth; canvas.height = window.innerHeight; });
class Particle{ constructor(){ this.x = Math.random()*canvas.width; this.y = Math.random()*canvas.height; this.size = Math.random()*2+0.5; this.speedX = Math.random()*0.5-0.25; this.speedY = Math.random()*0.5-0.25; this.opacity = Math.random()*0.5+0.2; } update(){ this.x+=this.speedX; this.y+=this.speedY; if(this.x>canvas.width) this.x=0; if(this.x<0) this.x=canvas.width; if(this.y>canvas.height) this.y=0; if(this.y<0) this.y=canvas.height; } draw(){ ctx.fillStyle = `rgba(160, 108, 213, ${this.opacity})`; ctx.beginPath(); ctx.arc(this.x,this.y,this.size,0,Math.PI*2); ctx.fill(); } }
const particles = []; for(let i=0;i<100;i++) particles.push(new Particle());
function animateParticles(){ ctx.clearRect(0,0,canvas.width,canvas.height); for(let i=0;i<particles.length;i++){ particles[i].update(); particles[i].draw(); for(let j=i+1;j<particles.length;j++){ const dx = particles[i].x - particles[j].x; const dy = particles[i].y - particles[j].y; const distance = Math.sqrt(dx*dx + dy*dy); if(distance<100){ ctx.strokeStyle = `rgba(160, 108, 213, ${0.1 * (1 - distance / 100)})`; ctx.lineWidth = 0.5; ctx.beginPath(); ctx.moveTo(particles[i].x, particles[i].y); ctx.lineTo(particles[j].x, particles[j].y); ctx.stroke(); } } } requestAnimationFrame(animateParticles); }
animateParticles();
const observerOptions = { threshold: 0.1, rootMargin: '0px 0px -50px 0px' };
const observer = new IntersectionObserver((entries)=>{ entries.forEach(entry=>{ if(entry.isIntersecting) entry.target.classList.add('animated'); }); }, observerOptions);
document.querySelectorAll('.animate-on-scroll').forEach(el=> observer.observe(el));
const showMoreBtn = document.getElementById('ctf-show-more'); const extraCards = document.querySelectorAll('[data-extra-card]'); let ctfExpanded = false; if(showMoreBtn && extraCards.length>0){ showMoreBtn.addEventListener('click', ()=>{ ctfExpanded = !ctfExpanded; extraCards.forEach(card => { if(ctfExpanded) card.classList.remove('hidden'); else card.classList.add('hidden'); }); const btnText = showMoreBtn.querySelector('[data-i18n="ctf.showMore"]'); const btnIcon = showMoreBtn.querySelector('span:last-child'); if(ctfExpanded){ btnText.setAttribute('data-i18n','ctf.showLess'); btnText.textContent = 'Voir moins'; btnIcon.textContent = '▲'; } else { btnText.setAttribute('data-i18n','ctf.showMore'); btnText.textContent = 'Voir plus'; btnIcon.textContent = '▼'; } }); }
let ticking = false; window.addEventListener('scroll', ()=>{ if(!ticking){ window.requestAnimationFrame(()=>{ const scrolled = window.pageYOffset; const parallaxElements = document.querySelectorAll('.float-animate:not(.profile-image-container)'); parallaxElements.forEach(el=>{ const speed = parseFloat(el.dataset.parallaxSpeed) || 0.3; const max = 40; const y = Math.max(Math.min(scrolled * speed, max), -max); el.style.transform = `translateY(${y}px)`; }); const profile = document.querySelector('.profile-image-container.float-animate'); if(profile){ const speed = 0.08; const y = Math.max(Math.min(scrolled * speed, 10), -10); profile.style.transform = `translateY(${y}px)`; } ticking = false; }); ticking = true; } });
document.querySelectorAll('.card-3d').forEach(card => { card.addEventListener('mousemove', (e)=>{ const rect = card.getBoundingClientRect(); const x = e.clientX - rect.left; const y = e.clientY - rect.top; const centerX = rect.width / 2; const centerY = rect.height / 2; const rotateX = (y - centerY) / 20; const rotateY = (centerX - x) / 20; card.style.transform = `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg) translateY(-5px) scale(1.02)`; }); card.addEventListener('mouseleave', ()=>{ card.style.transform = ''; }); });
function adjustBodyForFixedHeader(){ const nav = document.querySelector('nav'); const spacer = document.getElementById('nav-spacer'); if(nav && spacer){ const navHeight = nav.getBoundingClientRect().height; spacer.style.height = navHeight + 'px'; spacer.style.width = '100%'; } }
window.addEventListener('load', ()=>{ adjustBodyForFixedHeader(); const loadingBar = document.getElementById('loading-bar'); if(loadingBar){ setTimeout(()=>{ loadingBar.style.opacity = '0'; }, 2000); } }); window.addEventListener('resize', adjustBodyForFixedHeader);
const title = document.querySelector('h1'); if(title){ const text = title.textContent; title.textContent = ''; let i=0; const typeWriter = ()=>{ if(i<text.length){ title.textContent += text.charAt(i); i++; setTimeout(typeWriter, 100); } else { title.classList.remove('typing-effect'); } }; setTimeout(()=>{ title.classList.add('typing-effect'); typeWriter(); }, 500); }
// enforce nav top
(function(){ try{ const nav = document.querySelector('nav'); const spacer = document.getElementById('nav-spacer'); if(nav){ nav.style.position='fixed'; nav.style.top='0px'; nav.style.left='0px'; nav.style.right='0px'; nav.style.zIndex='10000'; } if(nav && spacer){ const h = nav.getBoundingClientRect().height; spacer.style.height = h + 'px'; spacer.style.width = '100%'; } document.documentElement.style.margin='0'; document.body.style.margin='0'; } catch(e){} })();

